version: '3'
services:
  web:
    image: tutorial
    build: .
    container_name: tutorial_drf_container
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    command: python3 manage.py runserver 0.0.0.0:8000

